### ISSUE TITLE
Running some games do not work

### ISSUE THREAD

**Issue by Croden1999** [Vita3K/Vita3K#1445]
Some games can running before v0.1.2 2209 https://github.com/Vita3K/Vita3K/commit/897892f31b05a036cf02d9aed424755ef8d78d44, but not working on v0.1.2 2209 and latest version.
![LFY29(SC3GRRWTQFL62N28I](https://user-images.githubusercontent.com/61804715/130351601-30e81d33-79d3-4a74-98b8-0ba2c43d47eb.png)

# Some games have this issue
AKIBA'S TRIP: U&U / AKIBA'S TRIP 2,
Shinobido 2: Revenge of Zen.
SUMION

**Comment by Croden1999** [comment]
I'll keep counting other games for this pr.

**Comment by Zangetsu38** [comment]
You have incomplete report, is what number build exactly ?

**Comment by Croden1999** [comment]
Actually from v0.1.2 2200 to v0.1.3 2264.

**Comment by Croden1999** [comment]
> You have incomplete report, is what number build exactly ?

Actually from v0.1.2 2200 to v0.1.3 2264. i want to submit this issue a month ago.

**Comment by Zangetsu38** [comment]
> > You have incomplete report, is what number build exactly ?
> 
> Actually from v0.1.2 2200 to v0.1.3 2264. and i wanted to submit this issue a month ago.

Last build ,près so is 2200 ?

**Comment by Croden1999** [comment]
> Last build works so is 2200 ?

not sure, because i testing the version is v0.1.2 2209 on 1st June.

**Comment by Zangetsu38** [comment]
> 
> 
> > Last build works so is 2200 ?
> 
> not sure, because i testing the version is v0.1.2 2209 [897892f](https://github.com/Vita3K/Vita3K/commit/897892f31b05a036cf02d9aed424755ef8d78d44) on 1st June.

check more, with test build out by build for found what buiol:d have broken

**Comment by Croden1999** [comment]
> > > Last build works so is 2200 ?
> > 
> > 
> > not sure, because i testing the version is v0.1.2 2209 [897892f](https://github.com/Vita3K/Vita3K/commit/897892f31b05a036cf02d9aed424755ef8d78d44) on 1st June.
> 
> check more, with test build out by build for found what buiol:d have broken

maybe i am wrong, not v0.1.2 2200 build, it is on v0.1.2 2209 https://github.com/Vita3K/Vita3K/commit/897892f31b05a036cf02d9aed424755ef8d78d44 build broken.

**Comment by Zangetsu38** [comment]
Interesting rapport for akiba régression @sunho can help you

**Comment by Croden1999** [comment]
> Interesting repport for akiba régression @sunho can help you

it is not just this game, some games have this problem

**Comment by Zangetsu38** [comment]
fixed by #1457

**Comment by Croden1999** [comment]
> fixed by #1457

thx a lot.

**Comment by Croden1999** [comment]
alright, the [EMPTY] still exists.
![Uploading -5af85a86a6fefa50.png…]()

**Comment by Croden1999** [comment]
alright, the [EMPTY] still exists.
![-5af85a86a6fefa50](https://user-images.githubusercontent.com/61804715/166618203-89ac7d8b-735f-45c8-aa3b-5e77395ac33d.png)
