### ISSUE TITLE
chmod a+x on Debian based [suggestion]

### ISSUE THREAD

**Issue by CoffeeBrewer64** [Vita3K/Vita3K#2383]
Both the Vita3K app and updater need chmod a+x done on them in order for it work, but no where does it say that you need to do it.

I have spent ages wondering why the updated doesn't work, and it was because of chmod not being ran on it.

It is so simple but missing and would seriously save people time.

You could say it's a lack of common sense on my part, but most apps I have ran on my system do not need chmod.

Specifics:

Debian 11 (Bullseye) Kali Linux 2022.LATEST

I don't know what a+x do, but they are the args I used for the vita3k apps.

**Comment by Macdu** [comment]
Fixed by #2295

**Comment by CoffeeBrewer64** [comment]
Please reopen, it is not fixed. I am still having to run chmod a+x, the pr didn't fix it.

**Comment by EXtremeExploit** [comment]
https://github.com/actions/upload-artifact/issues/38 seems to be the cause
