### ISSUE TITLE
can't open Vita3K

### ISSUE THREAD

**Issue by setsuna1126** [Vita3K/Vita3K#2405]
logging::exception_handler]: Exception 0xE06D7363 C++ EH exception. Not found

**Comment by Croden1999** [comment]
dynarmic & vulkan on welcome park
![image](https://user-images.githubusercontent.com/61804715/223389679-2ebd0d96-2071-4c17-8685-024d16a40dfd.png)

**Comment by bookmist** [comment]
Should be fixed in #2406

**Comment by Saramagrean** [comment]
Still happen. (Build 3047)

![Vita3K-Crash_b3047](https://user-images.githubusercontent.com/26355472/223688754-041a8bb8-69dd-4094-ba41-6bae61663aa8.jpg)

**Comment by Tenkoouu** [comment]
> Still happen. (Build 3047)
> 
> ![Vita3K-Crash_b3047](https://user-images.githubusercontent.com/26355472/223688754-041a8bb8-69dd-4094-ba41-6bae61663aa8.jpg)

The same happened to me
![1](https://user-images.githubusercontent.com/125415210/223691796-ffca33e9-753c-40bf-a45f-64c383eb21c5.png)

**Comment by bookmist** [comment]
Please check if there is still this bug on latest commit https://github.com/Vita3K/Vita3K/commit/215073063a6b85bf43653f195804d64cbf31cdc8 . I hope I fixed it now.

**Comment by Tenkoouu** [comment]
> Please check if there is still this bug on latest commit [2150730](https://github.com/Vita3K/Vita3K/commit/215073063a6b85bf43653f195804d64cbf31cdc8) . I hope I fixed it now.

I already have the latest version, and the same thing still happens to me

[vita3k.log](https://github.com/Vita3K/Vita3K/files/10949345/vita3k.log)

**Comment by Saramagrean** [comment]
Build 3053 Still crash on start game. 😅

Spec. i5-6200U, Intel HD Grahpics 520.

![Vita3K-3053-Crash](https://user-images.githubusercontent.com/26355472/224631356-cc1512de-f0ea-4844-90ec-c9d633c47f58.jpg)

**Comment by Zangetsu38** [comment]
@Saramagrean is what game ?

**Comment by Saramagrean** [comment]
It happens on every game I have. maybe a specific bug on Intel HD.

**Comment by Tenkoouu** [comment]
me too

**Comment by Tenkoouu** [comment]
I tried the new version, unfortunately still the same.

[21:32:22.238] |I| [config::init_config]: backend-renderer: Vulkan
[21:32:22.239] |I| [config::init_config]: log-level: 0
[21:32:22.267] |I| [SDL_main]: Vita3K v0.1.6 3054-f26cf12c
[21:32:22.267] |I| [SDL_main]: Number of logical CPU cores: 8
[21:32:22.267] |I| [SDL_main]: Available ram memory: 7820 MiB
[21:32:22.365] |I| [renderer::vulkan::VKState::create]: Vulkan device: Intel(R) UHD Graphics
[21:32:22.365] |I| [renderer::vulkan::VKState::create]: Driver version: 101.2115
[21:32:22.366] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled
[21:32:22.383] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Fifo

![1](https://user-images.githubusercontent.com/125415210/224878878-6935c408-564d-4022-a550-d07c8f81be3f.png)

[vita3k.log](https://github.com/Vita3K/Vita3K/files/10963637/vita3k.log)

**Comment by GamingDuckingalt** [comment]
Same issue for me whenever I load a game on Vita3K.
Still persistent on Bulid 3056.
Specs: Intel Celeron N3350, Intel Graphics 500

**Comment by FellowsheepOfThePlum** [comment]
Heya, I am having this issue as well. Restarted PC, and made sure the Microsoft C++ was up to date, and installed. No dice. Here's a screenshot of the log. 
![image](https://user-images.githubusercontent.com/132420173/235825256-b24fd004-f933-4424-826c-21a9c9afcdc0.png)

I uninstalled and reinstalled Vita3K and so far, so good. I can't download the Font firmware file, but I did get the PS Vita update firmware installed both times. Originally my emulator path was in apps, so I switched it to a specific empty folder in my downloads where I keep Vita3K. Any ideas on how to fix it if it happens again, or preventing it?

**Comment by bookmist** [comment]
Try to switch to opengl renderer. In config.yml file, replace `backend-renderer: Vulkan` to `backend-renderer: OpenGL`

**Comment by scribam** [comment]
@setsuna1126  is it still an issue with the latest version? can you post a new vita3k.log file using the latest version?
