### ISSUE TITLE
When a game started the emulator closes

### ISSUE THREAD

**Issue by ghost** [Vita3K/Vita3K#2410]
- Vita3k v0.1.6 3049-ea1b3837

- When a game started the emulator closes,only happens with vulkan,and the following error appears
![1](https://user-images.githubusercontent.com/125415210/223849076-760040da-24b6-44fd-aabc-5eaddce67a1e.png)

**Comment by bookmist** [comment]
What game?

**Comment by Tenkoouu** [comment]
> What game?

It has happened to me with:

Toukiden kiwami
WRC 5 FIA WORLD RALLY CHAMPIONSHIP
WRC 3 FIA World Rally Championship
BlazBlue ChronoPhantasma

**Comment by Tenkoouu** [comment]
> What game?

it happens to me with all my games

**Comment by bookmist** [comment]
Can you also show begin of the log? before game is started.

**Comment by Tenkoouu** [comment]
> 



> Can you also show begin of the log? before game is started.

You mean this?

[PCSE00467 - [Toukiden  Kiwami].log](https://github.com/Vita3K/Vita3K/files/10930288/PCSE00467.-.Toukiden.Kiwami.log)

**Comment by bookmist** [comment]
I mean something like this 
`[13:32:40.710] |I| [init_config]: backend-renderer: Vulkan
[13:32:40.711] |I| [init_config]: log-level: 0
[13:32:40.827] |I| [SDL_main]: Vita3K v0.1.6 3054-fd649335-bookmist/master_2
[13:32:40.828] |I| [SDL_main]: Number of logical CPU cores: 20
[13:32:40.828] |I| [SDL_main]: Available ram memory: 32624 MiB
[13:32:40.933] |I| [create]: Enabling vulkan validation layers (has a performance impact but allows better error messages)
[13:32:41.346] |I| [create]: Vulkan device: AMD Radeon HD 7800 Series
[13:32:41.346] |I| [create]: Driver version: 2.0.179
[13:32:41.549] |I| [setup]: Present mode: FifoRelaxed
[13:32:42.425] |W| [load_compat_app_db]: App with title ID PCSE00305 has an issue but no status label. Please check GitHub issue 1197 and request a status label to be added.
[13:32:42.426] |W| [load_compat_app_db]: App with title ID PCSD00079 has an issue but no status label. Please check GitHub issue 1195 and request a status label to be added.
[13:32:42.426] |W| [load_compat_app_db]: App with title ID PCSE00279 has an issue but no status label. Please check GitHub issue 1194 and request a status label to be added.
[13:32:42.472] |I| [load_app_icon]: Default icon found for App PSPS10028, [PspEmu] in path PSPS10028.
`
Problem can depends of gpu and memory mapping, so I want to know if memory mapping is on and what gpu you have.

**Comment by bookmist** [comment]
And thank you for log. 
`[05:21:39.352] |C| [renderer::vulkan::VKState::map_memory]: No coherent memory available for memory mapping, please report it to the devs!`
@Macdu

**Comment by bookmist** [comment]
Please check if there is still this bug on latest commit https://github.com/Vita3K/Vita3K/commit/215073063a6b85bf43653f195804d64cbf31cdc8 . I hope I fixed it now.

**Comment by Tenkoouu** [comment]
> Please check if there is still this bug on latest commit [2150730](https://github.com/Vita3K/Vita3K/commit/215073063a6b85bf43653f195804d64cbf31cdc8) . I hope I fixed it now.

I already have the latest version, and the same thing still happens to me

[vita3k.log](https://github.com/Vita3K/Vita3K/files/10949345/vita3k.log)

**Comment by Tenkoouu** [comment]
I tried the new version, unfortunately still the same.

[21:32:22.238] |I| [config::init_config]: backend-renderer: Vulkan
[21:32:22.239] |I| [config::init_config]: log-level: 0
[21:32:22.267] |I| [SDL_main]: Vita3K v0.1.6 3054-f26cf12c
[21:32:22.267] |I| [SDL_main]: Number of logical CPU cores: 8
[21:32:22.267] |I| [SDL_main]: Available ram memory: 7820 MiB
[21:32:22.365] |I| [renderer::vulkan::VKState::create]: Vulkan device: Intel(R) UHD Graphics
[21:32:22.365] |I| [renderer::vulkan::VKState::create]: Driver version: 101.2115
[21:32:22.366] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled
[21:32:22.383] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Fifo

![1](https://user-images.githubusercontent.com/125415210/224878050-5758de35-9b31-4d45-b5af-b194f4f85c7b.png)

[vita3k.log](https://github.com/Vita3K/Vita3K/files/10963637/vita3k.log)

**Comment by GamingDuckingalt** [comment]
the latest bulid should be fixed.

**Comment by Tenkoouu** [comment]
With the last update it finally fixed 👍

[08:07:27.918] |I| [config::init_config]: backend-renderer: Vulkan
[08:07:27.918] |I| [config::init_config]: log-level: 0
[08:07:27.945] |I| [SDL_main]: Vita3K v0.1.6 3069-73fc1be1
[08:07:27.945] |I| [SDL_main]: Number of logical CPU cores: 8
[08:07:27.945] |I| [SDL_main]: Available ram memory: 7820 MiB
[08:07:28.046] |I| [renderer::vulkan::VKState::create]: Vulkan device: Intel(R) UHD Graphics
[08:07:28.047] |I| [renderer::vulkan::VKState::create]: Driver version: 101.2115
[08:07:28.047] |I| [renderer::vulkan::VKState::create]: Memory mapping is enabled
[08:07:28.064] |I| [renderer::vulkan::ScreenRenderer::setup]: Present mode: Fifo

[vita3k.log](https://github.com/Vita3K/Vita3K/files/11068703/vita3k.log)

**Comment by scribam** [comment]
Issue marked as fixed from the author, closing
