### ISSUE TITLE
Error：Game crash when switching scenes

### ISSUE THREAD

**Issue by hp137057779** [Vita3K/Vita3K#2756]
Playing The "The Legend of Heroes Sora no Kiseki the 3rd"(英雄伝説：空の軌跡the 3rd) on vita3k emulator.
Game crash when switching scenes.

[vita3k.log](https://github.com/Vita3K/Vita3K/files/12075722/vita3k.log)

**Comment by johnwhite5116** [comment]
https://github.com/Vita3K/compatibility/issues/1048#issuecomment-1698321411

Still same issue.

I've finished FC and SC without any major issue.

It's a shame that I can't finish whole Trails in the Sky series on Vita3K.

**Comment by noxorious2001** [comment]
Crash when entering kloe monument on chapter 6

**Comment by Macdu** [comment]
Should be fixed by #3043, please re-open if this is not the case

**Comment by Moobeeart** [comment]
@Macdu Hi Macdu, I have updated Vita3k to the latest version on the site but I am still experiencing a crash when switching scenes.

Are there any other solutions that you suggest? Thanks!

**Comment by Macdu** [comment]
Please comment about game specific issues in their compatibility repository https://github.com/Vita3K/compatibility/issues/1048
