### ISSUE TITLE
gen-windows.bat throws "Could NOT find Boost" error

### ISSUE THREAD

**Issue by lowleveldata** [Vita3K/Vita3K#672]
```
PS H:\git\Vita3K> 9 | .\gen-windows.bat
Please choose your preferred Visual Studio version.
Press '9' for VS 2019 or '7' for VS 2017: 9
-- The C compiler identification is MSVC 19.25.28612.0
-- The CXX compiler identification is MSVC 19.25.28612.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Setting up ext-boost environment variables
Using Boost_VERSION: H:/git/Vita3K/external/boost
Using Boost_INCLUDE_DIRS: H:/git/Vita3K/external/boost/boost
Using Boost_LIBRARY_DIRS: H:/git/Vita3K/external/boost-build/lib
CMake Deprecation Warning at external/capstone/CMakeLists.txt:18 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Enabling CAPSTONE_ARM_SUPPORT
-- Build type: Release
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found SDL2: H:/git/Vita3K/external/sdl/windows/lib/x64/SDL2main.lib;H:/git/Vita3K/external/sdl/windows/lib/x64/SDL2.lib
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Using Release VC++ CRT: MD
-- Google Mock was not found - tests based on that will not build
-- Finding Git version for SPIRV-Cross.
-- Found Git: C:/Program Files/Git/bin/git.exe (found version "2.16.2.windows.1")
-- Git hash: a00dbe0d
configuring boost
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: filesystem program_options system) (found
  version "1.71.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindBoost.cmake:2145 (find_package_handle_standard_args)
  vita3k/CMakeLists.txt:33 (find_package)
  vita3k/CMakeLists.txt:46 (configure_boost)


-- Configuring incomplete, errors occurred!
See also "H:/git/Vita3K/build-windows/CMakeFiles/CMakeOutput.log".
See also "H:/git/Vita3K/build-windows/CMakeFiles/CMakeError.log".
```

Isn't it strange that it says `Could NOT find Boost` and `"found version "1.71.0"` in the same line? I have also noticed that `Boost_LIBRARY_DIRS: H:/git/Vita3K/external/boost-build/lib` does not actually exist. Could that be the cause?

Disclaimer: The git submodules have been init'd and updated

**Comment by Zangetsu38** [comment]
It want said found submodule but not found build

**Comment by ichisadashioko** [comment]
> `Could NOT find Boost (missing: filesystem program_options system)`

fixed for now with #686

**Comment by litvaOo** [comment]
Issue still persists, just checked with latest master.
Removing `external\boost-build` and re-running `gen-windows` helped for me

**Comment by ichisadashioko** [comment]
yeah `gen` scripts detect for built `boost` so it's probably built from a long time ago. I think building `boost` takes even longer than building `vita3k`.

**Comment by sunho** [comment]
```
git clean -dfx -f
git submodule update --init --recursive
```
Solves the issue. From @ichisadashioko

**Comment by crazii** [comment]
same error after successfully building boost.

> common.copy E:\Repo\Vita3K\external\boost-build\lib\cmake\boost_log_setup-1.72.0\libboost_log_setup-variant-vc141-mt-gd-x64-1_72-static.cmake
> ..\boost-build\boost\bin.v2\libs\log\build\msvc-14.1\debug\address-model-64\link-static\threadapi-win32\threading-multi\libboost_log_setup-variant-vc141-mt-gd-x64-1_72-static.cmake
>         1 file(s) copied.
> msvc.archive ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_test_exec_monitor-vc141-mt-gd-x64-1_72.lib
> boost-install.generate-cmake-variant- ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_test_exec_monitor-variant-vc141-mt-gd-x64-1_72-static.cmake
> msvc.archive ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_unit_test_framework-vc141-mt-gd-x64-1_72.lib
> boost-install.generate-cmake-variant- ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_unit_test_framework-variant-vc141-mt-gd-x64-1_72-static.cmake
> common.copy E:\Repo\Vita3K\external\boost-build\lib\libboost_test_exec_monitor-vc141-mt-gd-x64-1_72.lib
> ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_test_exec_monitor-vc141-mt-gd-x64-1_72.lib
>         1 file(s) copied.
> common.copy E:\Repo\Vita3K\external\boost-build\lib\cmake\boost_test_exec_monitor-1.72.0\libboost_test_exec_monitor-variant-vc141-mt-gd-x64-1_72-static.cmake
> ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_test_exec_monitor-variant-vc141-mt-gd-x64-1_72-static.cmake
>         1 file(s) copied.
> common.copy E:\Repo\Vita3K\external\boost-build\lib\libboost_unit_test_framework-vc141-mt-gd-x64-1_72.lib
> ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_unit_test_framework-vc141-mt-gd-x64-1_72.lib
>         1 file(s) copied.
> common.copy E:\Repo\Vita3K\external\boost-build\lib\cmake\boost_unit_test_framework-1.72.0\libboost_unit_test_framework-variant-vc141-mt-gd-x64-1_72-static.cmake
> ..\boost-build\boost\bin.v2\libs\test\build\msvc-14.1\debug\address-model-64\link-static\threading-multi\libboost_unit_test_framework-variant-vc141-mt-gd-x64-1_72-static.cmake
>         1 file(s) copied.
> ...updated 1194 targets...
> -- Selecting Windows SDK version 10.0.14393.0 to target Windows 10.0.18363.
> -- The C compiler identification is MSVC 19.16.27038.0
> -- The CXX compiler identification is MSVC 19.16.27038.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> Setting up ext-boost environment variables
> Using Boost_VERSION: E:/Repo/Vita3K/external/boost
> Using Boost_INCLUDE_DIRS: E:/Repo/Vita3K/external/boost/boost
> Using Boost_LIBRARY_DIRS: E:/Repo/Vita3K/external/boost-build/lib
> CMake Deprecation Warning at external/capstone/CMakeLists.txt:18 (cmake_policy):
>   The OLD behavior for policy CMP0048 will be removed from a future version
>   of CMake.
> 
>   The cmake-policies(7) manual explains that the OLD behaviors of all
>   policies are deprecated and that a policy should be set to OLD only under
>   specific short-term circumstances.  Projects should be ported to the NEW
>   behavior and not rely on setting a policy to OLD.
> 
> 
> Enabling CAPSTONE_ARM_SUPPORT
> -- Build type: Release
> -- Looking for pthread.h
> -- Looking for pthread.h - not found
> -- Found Threads: TRUE
> -- Found SDL2: E:/Repo/Vita3K/external/sdl/windows/lib/x64/SDL2main.lib;E:/Repo/Vita3K/external/sdl/windows/lib/x64/SDL2.lib
> -- Using Debug VC++ CRT: MDd
> -- Using Release VC++ CRT: MD
> -- Using MinSizeRel VC++ CRT: MD
> -- Using RelWithDebInfo VC++ CRT: MD
> -- Using Release VC++ CRT: MD
> -- SPIRV-Cross: Finding Git version for SPIRV-Cross.
> -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
> -- SPIRV-Cross: Git hash: 3c43f055
> CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
>   Could NOT find Boost (missing: system filesystem program_options) (found
>   version "1.72.0")
> Call Stack (most recent call first):
>   C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
>   C:/Program Files/CMake/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
>   external/psvpfstools/CMakeLists.txt:8 (FIND_PACKAGE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "E:/Repo/Vita3K/build-windows/CMakeFiles/CMakeOutput.log".
> See also "E:/Repo/Vita3K/build-windows/CMakeFiles/CMakeError.log".

**Comment by ichisadashioko** [comment]
@crazii I can see that you are using your own version of `cmake`. I highly recommend to use `cmake` that comes with Visual Studio. You can just open the `Developer Command Prompt for VS 2017` and `cmake` will be available from there. There is no need to install `cmake` - it comes with Visual Studio for best compatibility with others Visual Studio's toolchain.

**Comment by crazii** [comment]
> @crazii I can see that you are using your own version of `cmake`. I highly recommend to use `cmake` that comes with Visual Studio. You can just open the `Developer Command Prompt for VS 2017` and `cmake` will be available from there. There is no need to install `cmake` - it comes with Visual Studio for best compatibility with others Visual Studio's toolchain.

Cool, Thanks!

**Comment by crazii** [comment]
@ichisadashioko after using VS's cmake, it works. BTW my default(customized) installation doesn't have cmake, just run VS setup again and modify it, select `Individual components` tab and search cmake, and then toggle `Visual C++ tools for CMake`.
